chore: satify github branch protection rules (#259)
* chore: save release as draft

* chore: update build name

* chore: add additional step to satisfy github actions branch protection

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,6 +24,8 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: 'true'
+      - name: Update rustup
+        run: rustup update stable --no-self-update
       - name: Format check
         run: |
           rustup component add rustfmt
@@ -39,7 +41,7 @@ jobs:
         run: |
           cargo publish --dry-run -p csaf-rs --verbose --no-verify --locked
 
-  build:
+  build-matrix:
     needs: prepare
     permissions:
       contents: write
@@ -125,13 +127,27 @@ jobs:
           artifact-name: csaf-validator-${{ matrix.target.arch }}-${{ matrix.version }}-sbom.spdx.json
 
 
+  build-platforms:
+    needs: build-matrix
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check build status
+        run: |
+          if [ ${{ needs.build-matrix.result }} == 'success' ]; then
+            echo "All matrix builds succeeded."
+          else
+            echo "Some matrix builds failed."
+            exit 1
+          fi
+          
   publish-crates:
     runs-on: ubuntu-latest
     permissions:
       contents: read
       id-token: write    
     needs:
-      - build
+      - build-platforms
     if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')
     steps:
       - uses: actions/checkout@v4
@@ -141,6 +157,8 @@ jobs:
         run: ./update_assets.sh
       - uses: rust-lang/crates-io-auth-action@v1
         id: auth
+      - name: Update rustup
+        run: rustup update stable --no-self-update
       - name: Publish
         run: cargo publish --locked -p csaf-rs --verbose
         env:
@@ -184,7 +202,7 @@ jobs:
       contents: read
       id-token: write    
     needs:
-      - build
+      - build-platforms
     if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'beta') && !contains(github.ref, 'alpha')
     steps:
       - uses: actions/checkout@v4
